---
categories:
- Sequence Analysis
description: Gblocks
homepage_url: https://molevol-ibe.csic.es/Gblocks.html
name: gblocks
owner: earlhaminst
long_description: Selection of conserved blocks from multiple alignments for their use in phylogenetic analysis.
remote_repository_url: https://github.com/EarlhamInst/earlham-galaxytools/tree/main/tools/gblocks
type: unrestricted
